### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by TheDAS-designer** [Shard-Labs/starknet-devnet#12]
(env) xxxxx@xxxxxMacBook-Pro testProject % starknet-devnet
Traceback (most recent call last):
  File "/Users/xxxxx/devData/starkNet/testProject/env/bin/starknet-devnet", line 5, in <module>
    from starknet_devnet.server import main
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starknet_devnet/server.py", line 4, in <module>
    from starkware.starknet.services.api.gateway.transaction import Deploy, InvokeFunction, Transaction
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starknet/services/api/gateway/transaction.py", line 13, in <module>
    from services.everest.api.gateway.transaction import (
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/services/everest/api/gateway/transaction.py", line 5, in <module>
    from starkware.starkware_utils.validated_dataclass import ValidatedMarshmallowDataclass
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_dataclass.py", line 13, in <module>
    from starkware.starkware_utils.validated_fields import Field
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/validated_fields.py", line 12, in <module>
    from starkware.starkware_utils.marshmallow_dataclass_fields import (
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/starkware/starkware_utils/marshmallow_dataclass_fields.py", line 6, in <module>
    from frozendict import frozendict
  File "/Users/xxxxx/devData/starkNet/testProject/env/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

OS: MacOS 12.0.1
python: 3.10
 starknet-devnet: 0.1.6

**Comment by FabijanC** [comment]
When does this happen? How did you trigger it?

**Comment by FabijanC** [comment]
First try downgrading to starknet-devnet v0.1.5.
If that still fails, return to v0.1.6, but try with a lower version of Python (v3.9, v3.8, v3.7).

**Comment by FabijanC** [comment]
I've tried reproducing this locally and concluded that using Python 3.9 fixed the issue. It is now documented that Python 3.10 is not supported.
