### ISSUE TITLE
pip install starknet-devnet

### ISSUE THREAD

**Issue by qkaver** [Shard-Labs/starknet-devnet#129]
× Encountered error while trying to install package.
╰─> crypto-cpp-py

i've already brew install gmp
python3.8

**Comment by FabijanC** [comment]
@THenry14

**Comment by qkaver** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/19563358/173786395-611030ab-dae6-45d7-904b-832409debd91.png">

**Comment by THenry14** [comment]
Hi @qkaver, can you provide full output (preferably in text)? thanks.

**Comment by qkaver** [comment]
> 
hi @THenry14 
thank you for your help
nile init
Requirement already satisfied: ecdsa in ./env/lib/python3.8/site-packages (0.17.0)
Requirement already satisfied: fastecdsa in ./env/lib/python3.8/site-packages (2.2.3)
Requirement already satisfied: sympy in ./env/lib/python3.8/site-packages (1.10.1)
Requirement already satisfied: six>=1.9.0 in ./env/lib/python3.8/site-packages (from ecdsa) (1.16.0)
Requirement already satisfied: mpmath>=0.19 in ./env/lib/python3.8/site-packages (from sympy) (1.2.1)
🗄  Installing Cairo
Requirement already satisfied: cairo-lang in ./env/lib/python3.8/site-packages (0.9.0)
Collecting starknet-devnet
  Using cached starknet_devnet-0.2.3-py3-none-any.whl (174 kB)
Requirement already satisfied: aiohttp in ./env/lib/python3.8/site-packages (from cairo-lang) (3.8.1)
Requirement already satisfied: cachetools in ./env/lib/python3.8/site-packages (from cairo-lang) (5.2.0)
Requirement already satisfied: ecdsa in ./env/lib/python3.8/site-packages (from cairo-lang) (0.17.0)
Requirement already satisfied: eth-hash[pycryptodome] in ./env/lib/python3.8/site-packages (from cairo-lang) (0.3.2)
Requirement already satisfied: fastecdsa in ./env/lib/python3.8/site-packages (from cairo-lang) (2.2.3)
Requirement already satisfied: frozendict==1.2 in ./env/lib/python3.8/site-packages (from cairo-lang) (1.2)
Requirement already satisfied: lark-parser in ./env/lib/python3.8/site-packages (from cairo-lang) (0.12.0)
Requirement already satisfied: marshmallow-dataclass>=7.1.0 in ./env/lib/python3.8/site-packages (from cairo-lang) (8.5.8)
Requirement already satisfied: marshmallow-enum in ./env/lib/python3.8/site-packages (from cairo-lang) (1.5.1)
Requirement already satisfied: marshmallow-oneofschema in ./env/lib/python3.8/site-packages (from cairo-lang) (3.0.1)
Requirement already satisfied: marshmallow>=3.2.1 in ./env/lib/python3.8/site-packages (from cairo-lang) (3.16.0)
Requirement already satisfied: mpmath in ./env/lib/python3.8/site-packages (from cairo-lang) (1.2.1)
Requirement already satisfied: numpy in ./env/lib/python3.8/site-packages (from cairo-lang) (1.22.4)
Requirement already satisfied: pipdeptree in ./env/lib/python3.8/site-packages (from cairo-lang) (2.2.1)
Requirement already satisfied: prometheus-client in ./env/lib/python3.8/site-packages (from cairo-lang) (0.14.1)
Requirement already satisfied: pytest in ./env/lib/python3.8/site-packages (from cairo-lang) (7.1.2)
Requirement already satisfied: pytest-asyncio in ./env/lib/python3.8/site-packages (from cairo-lang) (0.18.3)
Requirement already satisfied: PyYAML in ./env/lib/python3.8/site-packages (from cairo-lang) (6.0)
Requirement already satisfied: sympy in ./env/lib/python3.8/site-packages (from cairo-lang) (1.10.1)
Requirement already satisfied: typeguard in ./env/lib/python3.8/site-packages (from cairo-lang) (2.13.3)
Requirement already satisfied: Web3 in ./env/lib/python3.8/site-packages (from cairo-lang) (5.29.2)
Requirement already satisfied: cloudpickle<2.2.0,>=2.1.0 in ./env/lib/python3.8/site-packages (from starknet-devnet) (2.1.0)
Requirement already satisfied: Werkzeug<2.1.0,>=2.0.3 in ./env/lib/python3.8/site-packages (from starknet-devnet) (2.0.3)
Requirement already satisfied: flask-cors<3.1.0,>=3.0.10 in ./env/lib/python3.8/site-packages (from starknet-devnet) (3.0.10)
Requirement already satisfied: Flask[async]<2.1.0,>=2.0.3 in ./env/lib/python3.8/site-packages (from starknet-devnet) (2.0.3)
Requirement already satisfied: meinheld<1.1.0,>=1.0.2 in ./env/lib/python3.8/site-packages (from starknet-devnet) (1.0.2)
Collecting crypto-cpp-py<1.1.0,>=1.0.4
  Using cached crypto_cpp_py-1.0.4.tar.gz (150 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Six in ./env/lib/python3.8/site-packages (from flask-cors<3.1.0,>=3.0.10->starknet-devnet) (1.16.0)
Requirement already satisfied: Jinja2>=3.0 in ./env/lib/python3.8/site-packages (from Flask[async]<2.1.0,>=2.0.3->starknet-devnet) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in ./env/lib/python3.8/site-packages (from Flask[async]<2.1.0,>=2.0.3->starknet-devnet) (2.1.2)
Requirement already satisfied: click>=7.1.2 in ./env/lib/python3.8/site-packages (from Flask[async]<2.1.0,>=2.0.3->starknet-devnet) (8.1.3)
Requirement already satisfied: asgiref>=3.2 in ./env/lib/python3.8/site-packages (from Flask[async]<2.1.0,>=2.0.3->starknet-devnet) (3.5.2)
Requirement already satisfied: packaging>=17.0 in ./env/lib/python3.8/site-packages (from marshmallow>=3.2.1->cairo-lang) (21.3)
Requirement already satisfied: typing-inspect>=0.7.1 in ./env/lib/python3.8/site-packages (from marshmallow-dataclass>=7.1.0->cairo-lang) (0.7.1)
Requirement already satisfied: greenlet<0.5,>=0.4.5 in ./env/lib/python3.8/site-packages (from meinheld<1.1.0,>=1.0.2->starknet-devnet) (0.4.17)
Requirement already satisfied: aiosignal>=1.1.2 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (1.7.2)
Requirement already satisfied: attrs>=17.3.0 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (21.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (1.3.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./env/lib/python3.8/site-packages (from aiohttp->cairo-lang) (2.0.12)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in ./env/lib/python3.8/site-packages (from eth-hash[pycryptodome]->cairo-lang) (3.14.1)
Requirement already satisfied: pip>=6.0.0 in ./env/lib/python3.8/site-packages (from pipdeptree->cairo-lang) (22.1.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./env/lib/python3.8/site-packages (from pytest->cairo-lang) (1.0.0)
Requirement already satisfied: py>=1.8.2 in ./env/lib/python3.8/site-packages (from pytest->cairo-lang) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in ./env/lib/python3.8/site-packages (from pytest->cairo-lang) (2.0.1)
Requirement already satisfied: iniconfig in ./env/lib/python3.8/site-packages (from pytest->cairo-lang) (1.1.1)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (2.1.1)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (1.1.7)
Requirement already satisfied: protobuf<4,>=3.10.0 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (3.20.1)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (2.3.0)
Requirement already satisfied: websockets<10,>=9.1 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (9.1)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (1.10.0)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (0.2.2)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (2.28.0)
Requirement already satisfied: jsonschema<5,>=3.2.0 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (4.6.0)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (0.8.0a2)
Requirement already satisfied: eth-account<0.6.0,>=0.5.7 in ./env/lib/python3.8/site-packages (from Web3->cairo-lang) (0.5.8)
Requirement already satisfied: multiaddr>=0.0.7 in ./env/lib/python3.8/site-packages (from ipfshttpclient==0.8.0a2->Web3->cairo-lang) (0.0.9)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in ./env/lib/python3.8/site-packages (from eth-abi<3.0.0,>=2.0.0b6->Web3->cairo-lang) (0.8.1)
Requirement already satisfied: bitarray<3,>=1.2.1 in ./env/lib/python3.8/site-packages (from eth-account<0.6.0,>=0.5.7->Web3->cairo-lang) (2.5.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in ./env/lib/python3.8/site-packages (from eth-account<0.6.0,>=0.5.7->Web3->cairo-lang) (0.5.1)
Requirement already satisfied: rlp<3,>=1.0.0 in ./env/lib/python3.8/site-packages (from eth-account<0.6.0,>=0.5.7->Web3->cairo-lang) (2.0.1)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in ./env/lib/python3.8/site-packages (from eth-account<0.6.0,>=0.5.7->Web3->cairo-lang) (0.2.1)
Requirement already satisfied: eth-keys<0.4.0,>=0.3.4 in ./env/lib/python3.8/site-packages (from eth-account<0.6.0,>=0.5.7->Web3->cairo-lang) (0.3.4)
Requirement already satisfied: cytoolz<1.0.0,>=0.10.1 in ./env/lib/python3.8/site-packages (from eth-utils<2.0.0,>=1.9.5->Web3->cairo-lang) (0.11.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib/python3.8/site-packages (from Jinja2>=3.0->Flask[async]<2.1.0,>=2.0.3->starknet-devnet) (2.1.1)
Requirement already satisfied: importlib-resources>=1.4.0 in ./env/lib/python3.8/site-packages (from jsonschema<5,>=3.2.0->Web3->cairo-lang) (5.7.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./env/lib/python3.8/site-packages (from jsonschema<5,>=3.2.0->Web3->cairo-lang) (0.18.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./env/lib/python3.8/site-packages (from packaging>=17.0->marshmallow>=3.2.1->cairo-lang) (3.0.9)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.8/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.8/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.8/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang) (1.26.9)
Requirement already satisfied: typing-extensions>=3.7.4 in ./env/lib/python3.8/site-packages (from typing-inspect>=0.7.1->marshmallow-dataclass>=7.1.0->cairo-lang) (4.2.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./env/lib/python3.8/site-packages (from typing-inspect>=0.7.1->marshmallow-dataclass>=7.1.0->cairo-lang) (0.4.3)
Requirement already satisfied: toolz>=0.8.0 in ./env/lib/python3.8/site-packages (from cytoolz<1.0.0,>=0.10.1->eth-utils<2.0.0,>=1.9.5->Web3->cairo-lang) (0.11.2)
Requirement already satisfied: zipp>=3.1.0 in ./env/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema<5,>=3.2.0->Web3->cairo-lang) (3.8.0)
Requirement already satisfied: varint in ./env/lib/python3.8/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang) (1.0.2)
Requirement already satisfied: base58 in ./env/lib/python3.8/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang) (2.1.1)
Requirement already satisfied: netaddr in ./env/lib/python3.8/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang) (0.8.0)
Building wheels for collected packages: crypto-cpp-py
  WARNING: Building wheel for crypto-cpp-py failed: [Errno 13] Permission denied: '/Users/qkaver/Library/Caches/pip/wheels/9e'
Failed to build crypto-cpp-py
Installing collected packages: crypto-cpp-py, starknet-devnet
  Running setup.py install for crypto-cpp-py ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for crypto-cpp-py did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running install
      running build
      running build_py
      running build_ext
      Targeting x86_64-apple-macos10.9
      cmake_minimum_required (VERSION 3.5)
      if (NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER /usr/bin/clang++)
      endif()
      
      project(StarkwareCryptoLib VERSION 0.1.0 LANGUAGES CXX)
      
      set(CMAKE_CXX_STANDARD 17)
      
      include(FetchContent)
      FetchContent_Declare(
        googletest
        URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
      )
      # For Windows: Prevent overriding the parent project's compiler/linker settings
      set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
      FetchContent_MakeAvailable(googletest)
      
      include(CTest)
      enable_testing()
      include_directories("${CMAKE_SOURCE_DIR}/src")
      
      if (NOT DEFINED CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Debug)
      endif()
      
      set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
      set(CMAKE_CXX_FLAGS "-std=c++17 -Werror -Wall -Wextra -fno-strict-aliasing -fPIC ${CMAKE_CXX_FLAGS} -target x86_64-apple-macos10.9")
      
      set(CC_OPTIMIZE "-O3")
      
      set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
      set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${CC_OPTIMIZE}")
      
      add_subdirectory(src)
      ./build_extension.sh: line 34: cmake: command not found
      sed: build/Release/_deps/googletest-src/CMakeLists.txt: No such file or directory
      make: *** No targets specified and no makefile found.  Stop.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vl/dj3myx150r729x71ctq_2jnm0000gn/T/pip-install-iotb6hu3/crypto-cpp-py_1c16d496a81948b68f417ba45922ca20/setup.py", line 48, in <module>
          setup(
        File "/Users/qkaver/test11/env/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/qkaver/test11/env/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/vl/dj3myx150r729x71ctq_2jnm0000gn/T/pip-install-iotb6hu3/crypto-cpp-py_1c16d496a81948b68f417ba45922ca20/setup.py", line 16, in run
          self.run_command("build_ext")
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/qkaver/test11/env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/vl/dj3myx150r729x71ctq_2jnm0000gn/T/pip-install-iotb6hu3/crypto-cpp-py_1c16d496a81948b68f417ba45922ca20/setup.py", line 30, in build_extension
          subprocess.run(
        File "/Users/qkaver/opt/anaconda3/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command './build_extension.sh' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> crypto-cpp-py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "/Users/qkaver/test11/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/nile/cli.py", line 61, in init
    init_command()
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/nile/core/init.py", line 19, in init
    install()
  File "/Users/qkaver/test11/env/lib/python3.8/site-packages/nile/core/install.py", line 10, in install
    subprocess.check_call(
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/qkaver/test11/env/bin/python3', '-m', 'pip', 'install', 'cairo-lang', 'starknet-devnet']' returned non-zero exit status 1.

**Comment by THenry14** [comment]
Hi @qkaver , It seems you are using an older macos version for which we did not release crypto-cpp-py wheels, the install attempts to build from source but fails because it cannot find cmake. To fix the issue, please run (in your virtual env, if you are using one):

`pip install crypto-cpp-py[build]`

That will install cmake, which should allow for install to pass. Please let me know if that helped.

**Comment by qkaver** [comment]
> pip install crypto-cpp-py[build]

@THenry14  It's been solved, that's really cool!!
thanks a lot :)
