### ISSUE TITLE
Version 0.1.8 throws error on start

### ISSUE THREAD

**Issue by Solpatium** [Shard-Labs/starknet-devnet#15]
## Issue

`MultiDict` doesn't support generic types, which results in error:
```
> poetry run starknet-devnet
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/.pyenv/versions/3.7.12/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/work/starknet/starknet-devnet/starknet_devnet/server.py", line 124, in <module>
    def check_block_hash(request_args: MultiDict[str, str]):
TypeError: 'type' object is not subscriptable
```

The same thing happens when using starknet-devnet as a package.

## Repro
```
git checkout v0.1.8
poetry run starknet-devnet
```

## Possible fix
After replacing `MultiDict[int, int]` with `MultiDict` in `starknet_devnet/server.py` it seems to be working properly. I can create a PR if needed.

**Comment by FabijanC** [comment]
Thanks for the report! Which version of Python are you using?

**Comment by Solpatium** [comment]
Ahh, sorry I forgot about it. I am using `Python 3.7.12`.

**Comment by FabijanC** [comment]
Hm, I would have expected that version to work. Anyway, you are welcome to create the PR.
