### ISSUE TITLE
Mint endpoint failes

### ISSUE THREAD

**Issue by ccarnino** [Shard-Labs/starknet-devnet#183]
**Describe the bug**
Mint api call returns a 500 error

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Try to Mint 1 Eth with Bravos wallet; or make POST /mint request to devnet with Postman

**Expected behavior**
Get some Eth minted to the account.

**Screenshots**
<img width="1074" alt="Screenshot 2022-07-18 at 11 52 04" src="https://user-images.githubusercontent.com/161903/179496645-b2c7e0ea-7ba8-4cea-808a-e5f7045d1cc5.png">

**Error Message in devnet logs***
```
[2022-07-18 11:43:21,765] ERROR in app: Exception on /mint [POST]
Traceback (most recent call last):
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/asgiref/sync.py", line 213, in __call__
    return call_result.result()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/asgiref/sync.py", line 279, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/starknet_devnet/blueprints/base.py", line 126, in mint
    tx_hash_int = await FeeToken.mint(address, amount, state.starknet_wrapper)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/starknet_devnet/fee_token.py", line 101, in mint
    assert cls.contract
AssertionError
```

**Devnet version**

- I am using Devnet version: 0.2.5
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**Machine specifications**

- OS: macOS Monterey 12.4.1
- CPU: Apple M1 Max
- Memory: 64GB

**Comment by FabijanC** [comment]
Not able to reproduce this. How did you start Devnet? Did you also by any chance load the devnet using the load feature, either with `--load-path` on startup or by sending a request to `/load`?

**Comment by ccarnino** [comment]
Is there an estimate date for this bug fix? thanks a lot

**Comment by FabijanC** [comment]
Sorry, work has been done at reduced capacity last week, but thanks for reminding about this. A fix probably won't be included in the next version, but the one after.

**Comment by ccarnino** [comment]
Thanks for working on this

**Comment by ccarnino** [comment]
Hello again.
I installed `0.2.7` since it seemed to include the bug fix.

Then I tried again to mint with the local faucet. I still get the same error:
```
"127.0.0.1 - - [03/Aug/2022:16:13:11 -0100] "POST /mint HTTP/1.1" 500 290 "-" "PostmanRuntime/7.29.2"
[2022-08-03 16:13:15,795] ERROR in app: Exception on /mint [POST]
Traceback (most recent call last):
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/asgiref/sync.py", line 213, in __call__
    return call_result.result()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/asgiref/sync.py", line 279, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/starknet_devnet/blueprints/base.py", line 145, in mint
    tx_hash = await state.starknet_wrapper.mint(
  File "/Users/claudio/.miniconda3/envs/starknet-dev-env/lib/python3.8/site-packages/starknet_devnet/starknet_wrapper.py", line 425, in mint
    transaction = self.__fee_token.get_mint_transaction(to_address, amount_uint256)
AttributeError: 'StarknetWrapper' object has no attribute '_StarknetWrapper__fee_token'
"127.0.0.1 - - [03/Aug/2022:16:13:15 -0100] "POST /mint HTTP/1.1" 500 290 "-" "PostmanRuntime/7.29.2"
```

**Comment by FabijanC** [comment]
Are you loading an old instance of Devnet (something that was dumped with a version before 0.2.7)? If so, that's not expected to work.

**Comment by ccarnino** [comment]
You are right. Deleting the dump file and restarting now works.
