### ISSUE TITLE
0.2.9 devnet restart breaks the devnet

### ISSUE THREAD

**Issue by microbecode** [Shard-Labs/starknet-devnet#221]
**Describe the bug**

After upgrading from 0.2.6 my unit tests fail completely.
My `before` hook restarts the devnet before anything else is done. If that line is active, all devnet invokes fail. After that, the devnet is terminally broken, until it is manually stopped and restarted - even if the restart line is removed.

I use the `lite-mode` in a venv.

**Not reproducible on alpha-goerli**

- [ x ] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Get the example repo branch: https://github.com/eqlabs/starknet-multisig/tree/feature/devnet_bug/contracts (the branch is a simplified branch of a bigger project)
2. Start devnet
3. Run tests

**Error message in devnet console**

`[2022-08-15 11:28:17,978] ERROR in app: Exception on /gateway/add_transaction [POST]
Traceback (most recent call last):
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/asgiref/sync.py", line 218, in __call__
    return call_result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/asgiref/sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/starknet_devnet/blueprints/gateway.py", line 35, in add_transaction
    contract_address, transaction_hash = await state.starknet_wrapper.deploy(transaction)
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/starknet_devnet/starknet_wrapper.py", line 253, in deploy
    state_update = await self.__update_state()
  File "/home/laurip/src/eqlabs/starknet-multisig/contracts/.venv/lib/python3.8/site-packages/starknet_devnet/starknet_wrapper.py", line 120, in __update_state
    assert previous_state is not None
AssertionError
"127.0.0.1 - - [15/Aug/2022:11:28:17 +0100] "POST /gateway/add_transaction HTTP/1.1" 500 290 "-" "Python/3.8 aiohttp/3.8.1"`

**Devnet version**

- I am using Devnet version: 0.2.9
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 0.2.6

**Machine specifications**

- OS: Windows, in WSL2

**Comment by FabijanC** [comment]
Fixed with https://github.com/Shard-Labs/starknet-devnet/pull/219. A new version that includes this fix (probably 0.2.10) will be released soon (today or tomorrow).
