### ISSUE TITLE
Internal error on get_full_contract

### ISSUE THREAD

**Issue by tabaktoni** [Shard-Labs/starknet-devnet#441]
**Describe the bug (observed vs expected behavior)**
Devnet Sequencer request on endpoint get_full_contract produces an internal server error.

```bash
[2023-04-06 08:54:16 +0000] [10] [INFO] 172.17.0.1 - - [06/Apr/2023:08:54:16 +0000] "GET /feeder_gateway/get_class_by_hash?classHash=0x345df0a9b35ce05d03772ba7938acad66921c5c39c1a5af74aee72aa25c363e&blockNumber=pending HTTP/1.1" 200 32749 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
[2023-04-06 08:54:20 +0000] [10] [ERROR] Exception on /feeder_gateway/get_full_contract [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/starknet_devnet/blueprints/feeder_gateway.py", line 207, in get_full_contract
    contract_class = await state.starknet_wrapper.get_class_by_address(
  File "/usr/local/lib/python3.9/site-packages/starknet_devnet/starknet_wrapper.py", line 737, in get_class_by_address
    return cached_state.contract_classes[class_hash]
KeyError: 1480390368599847860831167890933819330132643964535594925333154876542489998910
[2023-04-06 08:54:20 +0000] [10] [INFO] 172.17.0.1 - - [06/Apr/2023:08:54:20 +0000] "GET /feeder_gateway/get_full_contract?blockNumber=pending&contractAddress=0x551464a41b7a0adc71b2b7a4195618f9014e77ff323f1445dd3a3185eb6ad1b HTTP/1.1" 500 290 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

**Not reproducible on alpha-goerli**
On goerli it's works.

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Declare & Deploy Cairo 1 contract
2. request get_full_contract on deployed address

**Devnet version**
shardlabs/starknet-devnet:0.5.0a2-seed0
shardlabs/starknet-devnet:0.5.0a0-seed0

- I am using Devnet version:
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: not applicable for earlier versions

**Comment by mikiw** [comment]
I could reproduce it, thanks @tabaktoni
