### ISSUE TITLE
Crashes at launch (WERKZEUG_SERVER_FD)

### ISSUE THREAD

**Issue by alexandrewolff** [Shard-Labs/starknet-devnet#72]
Hello,

My instance crashes right at launch.

When I run ```starknet-devnet``` I get
```
Traceback (most recent call last):
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/bin/starknet-devnet", line 8, in <module>
    sys.exit(main())
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/starknet_devnet/server.py", line 329, in main
    app.run(host=args.host, port=args.port)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/werkzeug/serving.py", line 1047, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'
```

Same with `nile node`

```
Traceback (most recent call last):
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/bin/starknet-devnet", line 8, in <module>
    sys.exit(main())
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/starknet_devnet/server.py", line 329, in main
    app.run(host=args.host, port=args.port)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/werkzeug/serving.py", line 1047, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'
Traceback (most recent call last):
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/nile/cli.py", line 190, in node
    node_command(host, port)
  File "/Users/alexandre/code/alexandrewolff/nile-cairo-examples/env/lib/python3.8/site-packages/nile/core/node.py", line 21, in node
    subprocess.check_call(["starknet-devnet", "--host", host, "--port", str(port)])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['starknet-devnet', '--host', '127.0.0.1', '--port', '5000']' returned non-zero exit status 1.
```

I run on macOs 12.3.1 under apple m1 silicon cpu.

Any idea what causes that and how to fix ?

**Comment by badurinantun** [comment]
You can try running `pip install werkzeug==2.0.3`, this should fix the issue for now. Fix will should be deployed in the upcoming verison

**Comment by alexandrewolff** [comment]
Indeed it works now. Thanks !
